#if defined _ForwardsTest_included
 #endinput
#endif
#define _ForwardsTest_included

forward void MyForward_1(int index);
forward void MyForward_2(int index);
forward void MyForward_3(int index);
forward void MyForward_4(int index);
forward void MyForward_5(int index);
forward void MyForward_6(int index);
forward void MyForward_7(int index);
forward void MyForward_8(int index);
forward void MyForward_9(int index);
forward void MyForward_10(int index);
forward void MyForward_11(int index);
forward void MyForward_12(int index);
forward void MyForward_13(int index);
forward void MyForward_14(int index);
forward void MyForward_15(int index);
forward void MyForward_16(int index);
forward void MyForward_17(int index);
forward void MyForward_18(int index);
forward void MyForward_19(int index);
forward void MyForward_20(int index);
forward void MyForward_21(int index);
forward void MyForward_22(int index);
forward void MyForward_23(int index);
forward void MyForward_24(int index);
forward void MyForward_25(int index);
forward void MyForward_26(int index);
forward void MyForward_27(int index);
forward void MyForward_28(int index);
forward void MyForward_29(int index);
forward void MyForward_30(int index);
forward void MyForward_31(int index);
forward void MyForward_32(int index);
forward void MyForward_33(int index);
forward void MyForward_34(int index);
forward void MyForward_35(int index);
forward void MyForward_36(int index);
forward void MyForward_37(int index);
forward void MyForward_38(int index);
forward void MyForward_39(int index);
forward void MyForward_40(int index);
forward void MyForward_41(int index);
forward void MyForward_42(int index);
forward void MyForward_43(int index);
forward void MyForward_44(int index);
forward void MyForward_45(int index);
forward void MyForward_46(int index);
forward void MyForward_47(int index);
forward void MyForward_48(int index);
forward void MyForward_49(int index);
forward void MyForward_50(int index);
forward void MyForward_51(int index);
forward void MyForward_52(int index);
forward void MyForward_53(int index);
forward void MyForward_54(int index);
forward void MyForward_55(int index);
forward void MyForward_56(int index);
forward void MyForward_57(int index);
forward void MyForward_58(int index);
forward void MyForward_59(int index);
forward void MyForward_60(int index);
forward void MyForward_61(int index);
forward void MyForward_62(int index);
forward void MyForward_63(int index);
forward void MyForward_64(int index);
forward void MyForward_65(int index);
forward void MyForward_66(int index);
forward void MyForward_67(int index);
forward void MyForward_68(int index);
forward void MyForward_69(int index);
forward void MyForward_70(int index);
forward void MyForward_71(int index);
forward void MyForward_72(int index);
forward void MyForward_73(int index);
forward void MyForward_74(int index);
forward void MyForward_75(int index);


public SharedPlugin __pl_ForwardsTest= 
{
	name = "forwards_test",
	file = "forwards_test.smx",
#if defined REQUIRE_PLUGIN
	required = 1
#else
	required = 0
#endif
};
